# cibersecurity-desafio-ransomware
Desafio ransomware DIO

### Desafio concluído com sucesso

- Dentro da máquina virtual após download dos respectivos arquivos de teste, foi realizado corretamente o procedimento de criptografia e descriptografia dos arquivos
- Houve um pequeno problema de execução, mas foi resolvido. Se tratava da falta da biblioteca pyaes, mas posteriormente com pip install a biblioteca foi acionada e o código funcionou perfeitamente

![Captura de Tela (100)](https://user-images.githubusercontent.com/89417905/220379920-1d939f05-5206-49cc-bc68-4684ba41f14b.png)
![Captura de Tela (101)](https://user-images.githubusercontent.com/89417905/220379927-bf486931-91be-4890-8e9c-aa1063e0eb6d.png)
![Captura de Tela (102)](https://user-images.githubusercontent.com/89417905/220379931-6737300a-1794-451e-8ab4-ffc5b91f75c4.png)
![Captura de Tela (103)](https://user-images.githubusercontent.com/89417905/220379938-5591dc8d-e99e-48f6-9722-ccaa09b97cf7.png)
![Captura de Tela (104)](https://user-images.githubusercontent.com/89417905/220379942-9d20d943-69db-496e-b477-dcecb2902154.png)
![Captura de Tela (105)](https://user-images.githubusercontent.com/89417905/220379943-10903712-d102-4093-8a05-7bfe78b48855.png)
